"""
core/signal_processing.py — CSK Communication System Engine.

This is the centerpiece module of ChaosComm.  It implements the complete
chaotic shift keying communication chain:

    Message → Binary → Chaotic Carrier → Modulation → [Channel] → Detection → Decoded Message

Three modulation schemes:

1. CSK (Chaotic Shift Keying)
   - Bit 0 → chaotic sequence from parameter r₀
   - Bit 1 → chaotic sequence from parameter r₁
   - Receiver correlates with both templates, picks the higher
   - REQUIRES synchronization (receiver must know x₀ exactly)

2. DCSK (Differential Chaotic Shift Keying)
   - Each bit period split into two halves:
     Reference half:    r(t) = x(t)
     Information half:  i(t) = bₙ · x(t)    (bₙ ∈ {−1, +1})
   - Receiver correlates the two halves: z = Σ r[k]·i[k]
   - Decision: bₙ = sign(z)
   - NO synchronization needed — reference travels WITH the data
   - The key innovation: self-referencing eliminates the sync problem

3. FM-DCSK (Frequency-Modulated DCSK)
   - FM modulation of chaotic carrier: constant envelope
   - Better spectral properties, suitable for nonlinear amplifiers
   - Spreading factor β controls bandwidth/performance trade-off

Also included:
   - Waveform construction (pulse shaping)
   - ASCII ↔ binary encoding
   - Full pipeline: text message in → modulated waveform → detected bits → text out
   - Per-bit animation data for the frontend

LEARNER EXPLAINERS:
  CSK replaces a predictable carrier (sine wave) with an unpredictable
  one (chaotic sequence).  The transmitter and receiver share a secret:
  the map, the parameter, and the initial condition x₀.  Anyone who
  intercepts the signal sees what looks like noise — because chaos IS
  noise-like.  But the receiver, who knows the secret, can correlate
  the received signal with its own copy of the chaotic sequence and
  recover the bits.

  The catch: CSK requires the receiver to generate an EXACT replica of
  the chaotic sequence, which means perfect synchronization.  DCSK
  eliminates this by sending the reference alongside the data — at the
  cost of halving the data rate (half the bit period is "wasted" on the
  reference).  FM-DCSK adds FM modulation for a constant-envelope signal
  that plays nicer with real amplifiers.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np


# ===========================================================================
# CONCEPT EXPLAINERS
# ===========================================================================

CSK_EXPLAINERS: dict[str, str] = {
    "csk_overview": (
        "Chaotic Shift Keying (CSK) is analog to classical Binary Phase Shift "
        "Keying (BPSK), but instead of flipping a sine wave's phase, we switch "
        "between two chaotic sequences.  Bit 0 gets the sequence generated by "
        "parameter r₀; bit 1 gets the sequence from r₁.  The receiver holds "
        "templates for both and correlates: whichever template gives a higher "
        "correlation score is the detected bit.  The security advantage: without "
        "knowing x₀, an eavesdropper cannot build the templates."
    ),
    "dcsk_overview": (
        "Differential CSK (DCSK) solves CSK's synchronization problem.  Each bit "
        "period is split in half.  The first half transmits a raw chaotic reference "
        "segment; the second half transmits the SAME segment multiplied by ±1 "
        "(the data bit).  The receiver doesn't need its own chaotic generator — it "
        "just correlates the two halves: z = Σ r[k]·i[k].  If z > 0, the bit was +1; "
        "if z < 0, the bit was −1.  The trade-off: half the energy goes to the "
        "reference, so DCSK is ~3 dB worse than ideal coherent CSK in AWGN."
    ),
    "fmdcsk_overview": (
        "FM-DCSK uses frequency modulation to impose the chaotic signal onto a "
        "carrier: s(t) = A·cos(2πf_c·t + 2πΔf·∫x(τ)dτ).  The key advantage is "
        "CONSTANT ENVELOPE — the signal amplitude never changes, only its "
        "instantaneous frequency.  This means nonlinear power amplifiers (which "
        "are more efficient) can be used without distortion.  The spreading "
        "factor β = 2β_chips controls how many chaotic chips represent each bit; "
        "higher β means more processing gain but lower data rate."
    ),
    "synchronization_problem": (
        "The fundamental challenge of coherent CSK: the receiver must generate "
        "an EXACT copy of the transmitter's chaotic sequence.  But chaotic "
        "systems diverge exponentially from any initial-condition error (that's "
        "what λ > 0 means!).  So even 10⁻¹⁵ error in x₀ makes the receiver's "
        "copy useless after ~50 iterations.  Solutions: (1) DCSK — avoid sync "
        "entirely by sending the reference; (2) Pecora-Carroll synchronization — "
        "use a master-slave coupling where the transmitter 'drives' the "
        "receiver's oscillator until it locks on."
    ),
    "spreading_factor": (
        "The spreading factor β (or chips-per-bit) is the number of chaotic "
        "samples used to represent one bit.  Higher β means: more processing "
        "gain (each bit is spread over more chips, so noise is averaged out), "
        "better anti-jam resistance, but lower data rate (bandwidth goes up by "
        "β).  The optimal β depends on the channel: in clean AWGN, β = 1 is "
        "fine; in heavy jamming, β = 64+ may be needed."
    ),
    "correlation_detection": (
        "The receiver's core operation is correlation: multiply the received "
        "signal r[k] by a template s[k] and sum: z = Σ r[k]·s[k].  If the "
        "template matches the transmitted sequence, z is large (the chips "
        "reinforce).  If it doesn't match, z is small (the chips cancel "
        "randomly).  This is identical to the matched filter operation — "
        "correlation IS matched filtering sampled at the right instant."
    ),
    "waveform_construction": (
        "Before transmission, each quantized chaotic sample must be turned into "
        "a continuous-time waveform by multiplying it with a pulse shape φ(t).  "
        "The simplest pulse is a rectangular window (NRZ: Non-Return-to-Zero).  "
        "Better pulses (raised cosine, root-raised-cosine) reduce inter-symbol "
        "interference at the cost of bandwidth.  For our simulation we use NRZ "
        "pulses — each chip value is held constant for the chip duration T_c."
    ),
}


# ===========================================================================
# 1.  TEXT ↔ BINARY ENCODING
# ===========================================================================

def text_to_bits(text: str) -> list[int]:
    """Convert ASCII text to a flat list of bits (MSB first per character)."""
    bits = []
    for char in text:
        val = ord(char)
        for i in range(7, -1, -1):   # 8 bits per ASCII character
            bits.append((val >> i) & 1)
    return bits


def bits_to_text(bits: list[int]) -> str:
    """Convert a flat list of bits back to ASCII text."""
    chars = []
    for i in range(0, len(bits) - 7, 8):
        val = 0
        for j in range(8):
            val = (val << 1) | (1 if bits[i + j] > 0.5 else 0)
        chars.append(chr(val))
    return "".join(chars)


def analyze_bits(bits: list[int]) -> dict[str, Any]:
    """Compute Hamming weight, entropy, balance for the bit sequence."""
    n = len(bits)
    ones = sum(1 for b in bits if b == 1)
    zeros = n - ones
    p1 = ones / n if n > 0 else 0
    p0 = zeros / n if n > 0 else 0
    entropy = 0.0
    if p1 > 0: entropy -= p1 * math.log2(p1)
    if p0 > 0: entropy -= p0 * math.log2(p0)
    return {
        "n_bits": n,
        "ones": ones,
        "zeros": zeros,
        "hamming_weight": ones,
        "balance": ones / n if n > 0 else 0.5,
        "entropy": entropy,
    }


# ===========================================================================
# 2.  CHAOTIC SEQUENCE GENERATION (lightweight, no SymPy dependency)
# ===========================================================================

def _generate_chaotic_sequence(
    map_name: str,
    parameter: float,
    x0: float,
    length: int,
) -> np.ndarray:
    """
    Fast chaotic sequence generator for CSK.  No SymPy — pure NumPy
    scalar iteration for speed.  Supports the maps most commonly used
    for CSK: logistic, tent, pwlcm, chebyshev, sine, lss.
    """
    seq = np.empty(length, dtype=np.float64)
    x = float(x0)
    for i in range(length):
        seq[i] = x
        if map_name == "logistic":
            x = parameter * x * (1.0 - x)
        elif map_name == "tent":
            x = parameter * x if x < 0.5 else parameter * (1.0 - x)
        elif map_name == "pwlcm":
            p = parameter
            if x < p:
                x = x / p
            elif x < 0.5:
                x = (x - p) / (0.5 - p)
            elif x < 1.0 - p:
                x = (1.0 - p - x) / (0.5 - p)
            else:
                x = (1.0 - x) / p
        elif map_name == "chebyshev":
            n = int(parameter)
            x = math.cos(n * math.acos(max(-1, min(1, x))))
        elif map_name == "sine":
            x = (parameter / 4.0) * math.sin(math.pi * x)
        elif map_name == "lss":
            u = parameter * x * (1.0 - x) + (4.0 - parameter) * math.sin(math.pi * x) / 4.0
            x = u - math.floor(u)
        elif map_name == "tlc":
            tent = 2.0 * x if x < 0.5 else 2.0 * (1.0 - x)
            u = parameter * x * (1.0 - x) + (4.0 - parameter) * tent / 4.0
            x = u - math.floor(u)
        elif map_name == "cubic":
            x = parameter * x * (1.0 - x * x)
        elif map_name == "bernoulli":
            u = 2.0 * x
            x = u - math.floor(u)
        else:
            # Fallback: logistic
            x = 3.9 * x * (1.0 - x)

        # Safety: clamp to avoid escape
        if not math.isfinite(x):
            x = 0.5
        x = max(-1.5, min(1.5, x))

    return seq


# ===========================================================================
# 3.  WAVEFORM CONSTRUCTION
# ===========================================================================

def construct_waveform(
    chips: np.ndarray,
    samples_per_chip: int = 1,
) -> np.ndarray:
    """
    NRZ pulse shaping: each chip value is held constant for
    `samples_per_chip` samples.

    For CSK simulation at chip-rate sampling, samples_per_chip = 1
    (each chip is one sample).  For visualization at a higher sample
    rate, set samples_per_chip > 1 to see the rectangular pulses.
    """
    if samples_per_chip == 1:
        return chips.copy()
    return np.repeat(chips, samples_per_chip)


# ===========================================================================
# 4.  CSK MODULATION
# ===========================================================================

def csk_modulate(
    bits: list[int],
    map_name: str = "logistic",
    r0: float = 3.6,
    r1: float = 3.9,
    x0: float = 0.31415,
    chips_per_bit: int = 20,
) -> dict[str, Any]:
    """
    Coherent CSK modulation.

    Bit 0 → chaotic sequence from (map, r₀, x₀)
    Bit 1 → chaotic sequence from (map, r₁, x₀)

    Returns the modulated waveform + per-bit metadata for visualization.
    """
    n_bits = len(bits)
    total_chips = n_bits * chips_per_bit

    # Generate both template sequences
    seq0 = _generate_chaotic_sequence(map_name, r0, x0, total_chips)
    seq1 = _generate_chaotic_sequence(map_name, r1, x0, total_chips)

    # Build the transmitted waveform
    waveform = np.empty(total_chips, dtype=np.float64)
    per_bit = []
    for i, b in enumerate(bits):
        start = i * chips_per_bit
        end = start + chips_per_bit
        if b == 1:
            waveform[start:end] = seq1[start:end]
        else:
            waveform[start:end] = seq0[start:end]
        per_bit.append({
            "bit_index": i,
            "bit_value": int(b),
            "chip_start": start,
            "chip_end": end,
        })

    return {
        "scheme": "csk",
        "waveform": waveform.tolist(),
        "template_0": seq0.tolist(),
        "template_1": seq1.tolist(),
        "per_bit": per_bit,
        "n_bits": n_bits,
        "chips_per_bit": chips_per_bit,
        "total_chips": total_chips,
        "parameters": {"map": map_name, "r0": r0, "r1": r1, "x0": x0},
    }


def csk_detect(
    received: np.ndarray,
    template_0: np.ndarray,
    template_1: np.ndarray,
    chips_per_bit: int,
) -> dict[str, Any]:
    """
    CSK correlation detector.

    For each bit period, correlate received with both templates.
    Decision: bit = 1 if corr(r, s₁) > corr(r, s₀), else bit = 0.
    """
    n_bits = len(received) // chips_per_bit
    detected = []
    correlations = []

    for i in range(n_bits):
        start = i * chips_per_bit
        end = start + chips_per_bit
        r = received[start:end]
        c0 = float(np.dot(r, template_0[start:end]))
        c1 = float(np.dot(r, template_1[start:end]))
        bit = 1 if c1 > c0 else 0
        detected.append(bit)
        correlations.append({"bit": i, "corr_0": c0, "corr_1": c1, "decision": bit})

    return {
        "detected_bits": detected,
        "correlations": correlations,
        "n_bits": n_bits,
    }


# ===========================================================================
# 5.  DCSK MODULATION
# ===========================================================================

def dcsk_modulate(
    bits: list[int],
    map_name: str = "logistic",
    parameter: float = 3.9,
    x0: float = 0.31415,
    chips_per_half: int = 20,
) -> dict[str, Any]:
    """
    DCSK modulation — each bit period = reference half + information half.

    Reference:    r[k] = x[k]                  (raw chaotic)
    Information:  i[k] = b_n · x[k]            (b_n ∈ {−1, +1})

    where b_n = +1 for bit 1, b_n = −1 for bit 0.

    Total chips per bit = 2 × chips_per_half (half for reference, half
    for information).
    """
    n_bits = len(bits)
    chips_per_bit = 2 * chips_per_half
    total_chips = n_bits * chips_per_bit

    # Generate one long chaotic reference sequence
    ref_total = _generate_chaotic_sequence(map_name, parameter, x0, n_bits * chips_per_half)

    waveform = np.empty(total_chips, dtype=np.float64)
    per_bit = []

    for i, b in enumerate(bits):
        ref_start = i * chips_per_half
        ref_end = ref_start + chips_per_half
        ref_segment = ref_total[ref_start:ref_end]

        # Bipolar encoding: bit 1 → +1, bit 0 → −1
        b_sign = 1.0 if b == 1 else -1.0
        info_segment = b_sign * ref_segment

        # Place in waveform: [reference | information]
        wav_start = i * chips_per_bit
        waveform[wav_start:wav_start + chips_per_half] = ref_segment
        waveform[wav_start + chips_per_half:wav_start + chips_per_bit] = info_segment

        per_bit.append({
            "bit_index": i,
            "bit_value": int(b),
            "b_sign": float(b_sign),
            "ref_start": int(wav_start),
            "ref_end": int(wav_start + chips_per_half),
            "info_start": int(wav_start + chips_per_half),
            "info_end": int(wav_start + chips_per_bit),
            "ref_energy": float(np.sum(ref_segment ** 2)),
        })

    return {
        "scheme": "dcsk",
        "waveform": waveform.tolist(),
        "per_bit": per_bit,
        "n_bits": n_bits,
        "chips_per_half": chips_per_half,
        "chips_per_bit": chips_per_bit,
        "total_chips": total_chips,
        "parameters": {"map": map_name, "parameter": parameter, "x0": x0},
    }


def dcsk_detect(
    received: np.ndarray,
    chips_per_half: int,
) -> dict[str, Any]:
    """
    DCSK correlation detector.

    For each bit period:
      z = Σ r_ref[k] · r_info[k]
      decision = +1 if z > 0 else −1  →  bit = 1 if z > 0 else 0

    No templates needed — the reference IS in the received signal.
    """
    chips_per_bit = 2 * chips_per_half
    n_bits = len(received) // chips_per_bit
    detected = []
    correlations = []

    for i in range(n_bits):
        wav_start = i * chips_per_bit
        ref = received[wav_start:wav_start + chips_per_half]
        info = received[wav_start + chips_per_half:wav_start + chips_per_bit]
        z = float(np.dot(ref, info))
        bit = 1 if z > 0 else 0
        detected.append(bit)
        correlations.append({
            "bit": i,
            "correlation": z,
            "decision": bit,
            "ref_energy": float(np.sum(ref ** 2)),
        })

    return {
        "detected_bits": detected,
        "correlations": correlations,
        "n_bits": n_bits,
    }


# ===========================================================================
# 6.  FM-DCSK MODULATION
# ===========================================================================

def fmdcsk_modulate(
    bits: list[int],
    map_name: str = "logistic",
    parameter: float = 3.9,
    x0: float = 0.31415,
    chips_per_half: int = 20,
    fc: float = 10.0,           # carrier frequency (normalized)
    delta_f: float = 2.0,       # frequency deviation
    fs: float = 100.0,          # sample rate (normalized)
) -> dict[str, Any]:
    """
    FM-DCSK: frequency-modulate the chaotic carrier.

    s(t) = A · cos(2π·fc·t + 2π·Δf · ∫x(τ)dτ)

    Same DCSK structure (reference + information halves), but the
    baseband chaotic signal is FM-modulated for constant envelope.
    """
    n_bits = len(bits)
    chips_per_bit = 2 * chips_per_half

    # Generate baseband DCSK waveform first
    dcsk_result = dcsk_modulate(bits, map_name, parameter, x0, chips_per_half)
    baseband = np.asarray(dcsk_result["waveform"], dtype=np.float64)

    # Upsample to fs
    samples_per_chip = max(1, int(fs / chips_per_bit))
    baseband_up = np.repeat(baseband, samples_per_chip)
    total_samples = len(baseband_up)

    # FM modulate
    t = np.arange(total_samples) / fs
    phase = 2.0 * np.pi * delta_f * np.cumsum(baseband_up) / fs
    fm_signal = np.cos(2.0 * np.pi * fc * t + phase)

    return {
        "scheme": "fm_dcsk",
        "waveform_baseband": baseband.tolist(),
        "waveform_fm": fm_signal.tolist(),
        "per_bit": dcsk_result["per_bit"],
        "n_bits": n_bits,
        "chips_per_half": chips_per_half,
        "chips_per_bit": chips_per_bit,
        "total_samples": total_samples,
        "samples_per_chip": samples_per_chip,
        "parameters": {
            "map": map_name, "parameter": parameter, "x0": x0,
            "fc": fc, "delta_f": delta_f, "fs": fs,
        },
    }


# ===========================================================================
# 7.  FULL PIPELINE: message → modulate → (noiseless) → detect → message
# ===========================================================================

def full_pipeline(
    message: str,
    scheme: str = "dcsk",
    map_name: str = "logistic",
    parameter: float = 3.9,
    x0: float = 0.31415,
    chips_per_bit: int = 40,    # for CSK: chips_per_bit; for DCSK: 2×chips_per_half
    r0: float = 3.6,           # CSK only
    r1: float = 3.9,           # CSK only
) -> dict[str, Any]:
    """
    End-to-end noiseless pipeline.

    message → ASCII bits → modulate → detect (noiseless) → decode → recovered message

    Returns everything the frontend needs for the bit-by-bit animation.
    """
    # Encode
    bits = text_to_bits(message)
    bit_analysis = analyze_bits(bits)

    # Modulate
    if scheme == "csk":
        mod = csk_modulate(bits, map_name, r0, r1, x0, chips_per_bit)
        # Detect (noiseless: received = transmitted)
        received = np.asarray(mod["waveform"], dtype=np.float64)
        det = csk_detect(received,
                         np.asarray(mod["template_0"]),
                         np.asarray(mod["template_1"]),
                         chips_per_bit)
    elif scheme == "dcsk":
        half = chips_per_bit // 2
        mod = dcsk_modulate(bits, map_name, parameter, x0, half)
        received = np.asarray(mod["waveform"], dtype=np.float64)
        det = dcsk_detect(received, half)
    elif scheme == "fm_dcsk":
        half = chips_per_bit // 2
        mod = fmdcsk_modulate(bits, map_name, parameter, x0, half)
        # FM-DCSK detection: correlate the baseband (before FM) for noiseless demo
        baseband = np.asarray(mod["waveform_baseband"], dtype=np.float64)
        det = dcsk_detect(baseband, half)
    else:
        raise ValueError(f"Unknown scheme: {scheme}")

    # Decode
    recovered_text = bits_to_text(det["detected_bits"])

    # BER (should be 0 for noiseless)
    errors = sum(1 for a, b in zip(bits, det["detected_bits"]) if a != b)
    ber = errors / len(bits) if len(bits) > 0 else 0.0

    return {
        "message": message,
        "scheme": scheme,
        "bits": bits,
        "bit_analysis": bit_analysis,
        "modulation": {
            "scheme": mod["scheme"],
            "waveform": mod["waveform"] if "waveform" in mod else mod.get("waveform_baseband"),
            "per_bit": mod["per_bit"],
            "n_bits": mod["n_bits"],
            "chips_per_bit": mod.get("chips_per_bit", chips_per_bit),
            "total_chips": mod.get("total_chips", mod.get("total_samples")),
            "parameters": mod["parameters"],
        },
        "detection": det,
        "recovered_text": recovered_text,
        "ber": ber,
        "n_errors": errors,
        "success": recovered_text == message,
    }


# ===========================================================================
# 8.  SPECTRUM ANALYSIS (PSD of the modulated waveform)
# ===========================================================================

def compute_psd(waveform: np.ndarray, fs: float = 1.0) -> dict[str, Any]:
    """
    Power spectral density via Welch's method.

    Returns freq and PSD arrays for plotting.  Also computes spectral
    flatness (Wiener entropy): the ratio of geometric mean to arithmetic
    mean of the PSD — 1.0 = perfectly flat (white noise), <1 = has
    spectral structure.
    """
    from scipy.signal import welch

    nperseg = min(256, len(waveform) // 2)
    if nperseg < 16:
        return {"freq": [], "psd": [], "spectral_flatness": 0.0}

    freq, psd = welch(waveform, fs=fs, nperseg=nperseg)
    psd = np.maximum(psd, 1e-30)  # avoid log(0)

    # Spectral flatness
    log_mean = np.mean(np.log(psd))
    arith_mean = np.mean(psd)
    spectral_flatness = float(np.exp(log_mean) / arith_mean) if arith_mean > 0 else 0.0

    return {
        "freq": freq.tolist(),
        "psd": (10 * np.log10(psd)).tolist(),   # dB scale
        "spectral_flatness": spectral_flatness,
        "spectral_flatness_db": float(10 * np.log10(spectral_flatness + 1e-30)),
    }


def get_csk_explainers() -> dict[str, str]:
    return CSK_EXPLAINERS